services:
  backend:
    build:
      context: ./backend
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID:-${USER_ID}}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PORT=5000
    user: "${USER_ID}:${GROUP_ID:-${USER_ID}}"
    command: ["python", "server.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID:-${USER_ID}}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
      - CI=true
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID:-${USER_ID}}
    command: ["/bin/bash", "/app/entrypoint.sh"]
    user: "${USER_ID}:${GROUP_ID:-${USER_ID}}"

